version: '3'
services:
  api:
    build: ./backend
    volumes:
      - ./backend:/code

  front:
    build: ./frontend
    volumes:
      - ./frontend:/frontend

  proxy:
    build: ./proxy
    ports:
      - '8080:80'