version: '3'
services:
  api:
    build: ./backend
    container_name: api
    volumes:
      - ./backend:/code

  websocket:
    build: ./websocket
    container_name: websocket
    ports:
      - '8000:8000'
    volumes:
      - ./websocket:/code

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/home/static

  proxy:
    build: ./proxy
    container_name: proxy
    volumes:
      - ./proxy:/etc/nginx/conf.d
    ports:
      - '8080:80'